export const data = [
  {
    course_name: "Right-sized multimedia Graphical User Interface",
    course_description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    course_length: 6955,
    course_par: 70,
    course_slope: 102,
    course_address: "63 Goodland Park",
    course_city: "Saltsjö-Boo",
    course_state: "AB",
  },
  {
    course_name: "Persevering mobile intranet",
    course_description:
      "Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    course_length: 5814,
    course_par: 70,
    course_slope: 87,
    course_address: "7388 Tony Court",
    course_city: "Gombang",
    course_state: null,
  },
  {
    course_name: "Mandatory uniform initiative",
    course_description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    course_length: 5247,
    course_par: 72,
    course_slope: 119,
    course_address: "1 Mockingbird Street",
    course_city: "Basseterre",
    course_state: null,
  },
  {
    course_name: "Reverse-engineered well-modulated groupware",
    course_description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    course_length: 6666,
    course_par: 72,
    course_slope: 109,
    course_address: "35 Cascade Trail",
    course_city: "Pasirhaur",
    course_state: null,
  },
  {
    course_name: "Open-source grid-enabled migration",
    course_description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    course_length: 6980,
    course_par: 70,
    course_slope: 152,
    course_address: "7 Ronald Regan Street",
    course_city: "Clarence-Rockland",
    course_state: "ON",
  },
  {
    course_name: "Compatible real-time workforce",
    course_description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    course_length: 5568,
    course_par: 72,
    course_slope: 95,
    course_address: "8 Blackbird Drive",
    course_city: "Sukamulya",
    course_state: null,
  },
  {
    course_name: "Cloned bandwidth-monitored synergy",
    course_description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    course_length: 7403,
    course_par: 69,
    course_slope: 138,
    course_address: "9606 Hovde Court",
    course_city: "Slobodnica",
    course_state: null,
  },
  {
    course_name: "Enterprise-wide analyzing implementation",
    course_description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    course_length: 5889,
    course_par: 71,
    course_slope: 129,
    course_address: "8434 Helena Way",
    course_city: "Macari",
    course_state: null,
  },
  {
    course_name: "Object-based upward-trending instruction set",
    course_description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    course_length: 6135,
    course_par: 72,
    course_slope: 86,
    course_address: "587 Oriole Park",
    course_city: "Manay",
    course_state: null,
  },
  {
    course_name: "Universal heuristic contingency",
    course_description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    course_length: 6152,
    course_par: 69,
    course_slope: 93,
    course_address: "61375 Buhler Road",
    course_city: "Hiroshima-shi",
    course_state: null,
  },
  {
    course_name: "Compatible maximized secured line",
    course_description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    course_length: 7167,
    course_par: 71,
    course_slope: 88,
    course_address: "150 Merchant Way",
    course_city: "Rumbek",
    course_state: null,
  },
  {
    course_name: "Ameliorated asymmetric flexibility",
    course_description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    course_length: 7857,
    course_par: 70,
    course_slope: 117,
    course_address: "8 Johnson Pass",
    course_city: "Maddela",
    course_state: null,
  },
  {
    course_name: "Profound exuding support",
    course_description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    course_length: 7684,
    course_par: 69,
    course_slope: 58,
    course_address: "841 Del Sol Circle",
    course_city: "Shuren",
    course_state: null,
  },
  {
    course_name: "Virtual neutral portal",
    course_description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    course_length: 6604,
    course_par: 70,
    course_slope: 131,
    course_address: "3 Dottie Parkway",
    course_city: "Duobaoshan",
    course_state: null,
  },
  {
    course_name: "Virtual attitude-oriented service-desk",
    course_description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    course_length: 5555,
    course_par: 69,
    course_slope: 91,
    course_address: "16 Quincy Junction",
    course_city: "Trélazé",
    course_state: "B5",
  },
  {
    course_name: "Polarised actuating customer loyalty",
    course_description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    course_length: 6754,
    course_par: 70,
    course_slope: 120,
    course_address: "25210 Eastlawn Way",
    course_city: "Pogwizdów",
    course_state: null,
  },
  {
    course_name: "Function-based next generation access",
    course_description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    course_length: 7513,
    course_par: 70,
    course_slope: 147,
    course_address: "24 David Junction",
    course_city: "Fort Wayne",
    course_state: "IN",
  },
  {
    course_name: "Total holistic website",
    course_description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    course_length: 5741,
    course_par: 72,
    course_slope: 143,
    course_address: "05 Bultman Junction",
    course_city: "Paseh",
    course_state: null,
  },
  {
    course_name: "Adaptive tangible methodology",
    course_description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    course_length: 5935,
    course_par: 70,
    course_slope: 102,
    course_address: "3168 Killdeer Alley",
    course_city: "Göteborg",
    course_state: "O",
  },
  {
    course_name: "Multi-layered bifurcated policy",
    course_description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    course_length: 5228,
    course_par: 71,
    course_slope: 139,
    course_address: "51 Bluestem Park",
    course_city: "Beylagan",
    course_state: null,
  },
  {
    course_name: "Multi-channelled object-oriented Graphical User Interface",
    course_description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    course_length: 5872,
    course_par: 72,
    course_slope: 81,
    course_address: "447 Farmco Drive",
    course_city: "Hotsk",
    course_state: null,
  },
  {
    course_name: "Fully-configurable zero defect challenge",
    course_description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    course_length: 5181,
    course_par: 69,
    course_slope: 84,
    course_address: "34 American Ash Junction",
    course_city: "Jibiya",
    course_state: null,
  },
  {
    course_name: "Programmable methodical framework",
    course_description:
      "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    course_length: 6476,
    course_par: 70,
    course_slope: 62,
    course_address: "77074 John Wall Terrace",
    course_city: "Huangtan",
    course_state: null,
  },
  {
    course_name: "Operative bandwidth-monitored alliance",
    course_description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    course_length: 7098,
    course_par: 69,
    course_slope: 135,
    course_address: "4 Amoth Crossing",
    course_city: "Stockholm",
    course_state: "AB",
  },
  {
    course_name: "Realigned 4th generation hub",
    course_description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    course_length: 6540,
    course_par: 71,
    course_slope: 75,
    course_address: "862 Spohn Alley",
    course_city: "Batuidu",
    course_state: null,
  },
  {
    course_name: "Horizontal radical workforce",
    course_description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    course_length: 5587,
    course_par: 72,
    course_slope: 99,
    course_address: "7485 Anniversary Court",
    course_city: "Nancheng",
    course_state: null,
  },
  {
    course_name: "Adaptive actuating utilisation",
    course_description:
      "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    course_length: 5582,
    course_par: 72,
    course_slope: 121,
    course_address: "4 Mcbride Alley",
    course_city: "Condega",
    course_state: null,
  },
  {
    course_name: "Balanced methodical Graphical User Interface",
    course_description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    course_length: 6366,
    course_par: 70,
    course_slope: 109,
    course_address: "4597 Laurel Alley",
    course_city: "Bagou",
    course_state: null,
  },
  {
    course_name: "Vision-oriented didactic orchestration",
    course_description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    course_length: 6295,
    course_par: 70,
    course_slope: 71,
    course_address: "1110 Summer Ridge Drive",
    course_city: "Stockholm",
    course_state: "AB",
  },
  {
    course_name: "Focused value-added extranet",
    course_description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    course_length: 6704,
    course_par: 71,
    course_slope: 112,
    course_address: "131 4th Hill",
    course_city: "Tengrela",
    course_state: null,
  },
  {
    course_name: "Right-sized fresh-thinking pricing structure",
    course_description:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    course_length: 5826,
    course_par: 70,
    course_slope: 75,
    course_address: "724 Dawn Court",
    course_city: "Clanwilliam",
    course_state: null,
  },
  {
    course_name: "Expanded scalable core",
    course_description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    course_length: 7262,
    course_par: 70,
    course_slope: 124,
    course_address: "4292 Kings Crossing",
    course_city: "Huayucachi",
    course_state: null,
  },
  {
    course_name: "Total next generation neural-net",
    course_description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    course_length: 7484,
    course_par: 69,
    course_slope: 148,
    course_address: "25107 Green Road",
    course_city: "Kibiti",
    course_state: null,
  },
  {
    course_name: "Reduced bottom-line functionalities",
    course_description:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    course_length: 6255,
    course_par: 69,
    course_slope: 138,
    course_address: "2435 Bonner Alley",
    course_city: "Vlkoš",
    course_state: null,
  },
  {
    course_name: "Synergistic composite archive",
    course_description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    course_length: 5619,
    course_par: 70,
    course_slope: 143,
    course_address: "286 Swallow Pass",
    course_city: "Changshan",
    course_state: null,
  },
  {
    course_name: "Progressive even-keeled encoding",
    course_description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    course_length: 5337,
    course_par: 70,
    course_slope: 113,
    course_address: "49479 Moose Hill",
    course_city: "Westonaria",
    course_state: null,
  },
  {
    course_name: "Seamless transitional customer loyalty",
    course_description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    course_length: 5008,
    course_par: 70,
    course_slope: 55,
    course_address: "74 Iowa Circle",
    course_city: "Várzea da Serra",
    course_state: "18",
  },
  {
    course_name: "Devolved non-volatile groupware",
    course_description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    course_length: 6967,
    course_par: 72,
    course_slope: 73,
    course_address: "20746 Lillian Pass",
    course_city: "Bang Kruai",
    course_state: null,
  },
  {
    course_name: "Future-proofed executive definition",
    course_description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    course_length: 6201,
    course_par: 69,
    course_slope: 103,
    course_address: "239 Thackeray Street",
    course_city: "Kolape",
    course_state: null,
  },
  {
    course_name: "Customer-focused modular initiative",
    course_description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    course_length: 6712,
    course_par: 69,
    course_slope: 75,
    course_address: "86995 Mcguire Trail",
    course_city: "Raposos",
    course_state: null,
  },
  {
    course_name: "Synergized executive info-mediaries",
    course_description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    course_length: 7513,
    course_par: 71,
    course_slope: 90,
    course_address: "1 Orin Plaza",
    course_city: "Daliyuan",
    course_state: null,
  },
  {
    course_name: "Diverse 6th generation monitoring",
    course_description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    course_length: 7587,
    course_par: 71,
    course_slope: 150,
    course_address: "857 Stuart Crossing",
    course_city: "Dhromolaxia",
    course_state: null,
  },
  {
    course_name: "Team-oriented global internet solution",
    course_description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    course_length: 5385,
    course_par: 71,
    course_slope: 123,
    course_address: "11 Acker Parkway",
    course_city: "São Mamede",
    course_state: "01",
  },
  {
    course_name: "Public-key tangible internet solution",
    course_description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    course_length: 7815,
    course_par: 70,
    course_slope: 132,
    course_address: "4 Forster Park",
    course_city: "La Dorada",
    course_state: null,
  },
  {
    course_name: "Re-contextualized needs-based projection",
    course_description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    course_length: 7504,
    course_par: 72,
    course_slope: 139,
    course_address: "2093 Moland Point",
    course_city: "Musan-ŭp",
    course_state: null,
  },
  {
    course_name: "Ameliorated mission-critical migration",
    course_description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    course_length: 5812,
    course_par: 69,
    course_slope: 97,
    course_address: "44654 Armistice Terrace",
    course_city: "Las Matas de Farfán",
    course_state: null,
  },
  {
    course_name: "Future-proofed full-range contingency",
    course_description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    course_length: 5812,
    course_par: 70,
    course_slope: 150,
    course_address: "57 Anzinger Parkway",
    course_city: "Šluknov",
    course_state: null,
  },
  {
    course_name: "Adaptive mission-critical hub",
    course_description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    course_length: 6808,
    course_par: 72,
    course_slope: 77,
    course_address: "2609 Westend Center",
    course_city: "Qianwei",
    course_state: null,
  },
  {
    course_name: "Open-architected encompassing website",
    course_description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    course_length: 5724,
    course_par: 72,
    course_slope: 66,
    course_address: "13 Melvin Place",
    course_city: "Hayama",
    course_state: null,
  },
  {
    course_name: "Front-line exuding protocol",
    course_description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    course_length: 6180,
    course_par: 70,
    course_slope: 98,
    course_address: "94425 Chive Plaza",
    course_city: "Tewulike",
    course_state: null,
  },
  {
    course_name: "Robust fault-tolerant local area network",
    course_description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    course_length: 5786,
    course_par: 69,
    course_slope: 121,
    course_address: "39 Mandrake Terrace",
    course_city: "Vođinci",
    course_state: null,
  },
  {
    course_name: "Ergonomic 24 hour ability",
    course_description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    course_length: 6849,
    course_par: 72,
    course_slope: 107,
    course_address: "360 Starling Road",
    course_city: "Beit Jann",
    course_state: null,
  },
  {
    course_name: "Re-contextualized systemic time-frame",
    course_description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    course_length: 5872,
    course_par: 71,
    course_slope: 138,
    course_address: "3 Valley Edge Trail",
    course_city: "Nowshahr",
    course_state: null,
  },
  {
    course_name: "Virtual web-enabled middleware",
    course_description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    course_length: 6955,
    course_par: 69,
    course_slope: 130,
    course_address: "698 Bowman Junction",
    course_city: "Staryy Krym",
    course_state: null,
  },
  {
    course_name: "Automated fault-tolerant strategy",
    course_description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    course_length: 7126,
    course_par: 70,
    course_slope: 63,
    course_address: "83 Monica Center",
    course_city: "Cernache do Bonjardim",
    course_state: "05",
  },
  {
    course_name: "Pre-emptive multi-tasking collaboration",
    course_description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    course_length: 6386,
    course_par: 72,
    course_slope: 126,
    course_address: "15 Comanche Drive",
    course_city: "Daqingshan",
    course_state: null,
  },
  {
    course_name: "Polarised value-added utilisation",
    course_description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    course_length: 6424,
    course_par: 70,
    course_slope: 98,
    course_address: "1 Declaration Park",
    course_city: "E’zhou",
    course_state: null,
  },
  {
    course_name: "Function-based human-resource synergy",
    course_description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    course_length: 5690,
    course_par: 71,
    course_slope: 123,
    course_address: "186 Fulton Plaza",
    course_city: "Xiniu",
    course_state: null,
  },
  {
    course_name: "Integrated solution-oriented strategy",
    course_description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    course_length: 6873,
    course_par: 71,
    course_slope: 85,
    course_address: "839 Eagan Road",
    course_city: "Chum Phae",
    course_state: null,
  },
  {
    course_name: "Automated asynchronous ability",
    course_description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    course_length: 6449,
    course_par: 70,
    course_slope: 106,
    course_address: "959 Hermina Road",
    course_city: "Imari",
    course_state: null,
  },
  {
    course_name: "Inverse coherent help-desk",
    course_description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    course_length: 5391,
    course_par: 69,
    course_slope: 111,
    course_address: "4 Heffernan Junction",
    course_city: "Bebandem",
    course_state: null,
  },
  {
    course_name: "Proactive asymmetric task-force",
    course_description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    course_length: 7157,
    course_par: 72,
    course_slope: 82,
    course_address: "158 Nova Plaza",
    course_city: "Kowale Oleckie",
    course_state: null,
  },
  {
    course_name: "Polarised intangible toolset",
    course_description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    course_length: 5908,
    course_par: 69,
    course_slope: 103,
    course_address: "93 Fairfield Way",
    course_city: "Samir",
    course_state: null,
  },
  {
    course_name: "Reactive leading edge project",
    course_description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    course_length: 7877,
    course_par: 69,
    course_slope: 84,
    course_address: "37361 Red Cloud Junction",
    course_city: "Kaskinen",
    course_state: null,
  },
  {
    course_name: "Persistent zero defect hub",
    course_description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    course_length: 5098,
    course_par: 70,
    course_slope: 104,
    course_address: "07775 Butterfield Street",
    course_city: "Jingzhou",
    course_state: null,
  },
  {
    course_name: "Centralized 4th generation synergy",
    course_description: "Fusce consequat. Nulla nisl. Nunc nisl.",
    course_length: 7989,
    course_par: 70,
    course_slope: 128,
    course_address: "0 Westerfield Road",
    course_city: "Samokov",
    course_state: null,
  },
  {
    course_name: "Synergistic static middleware",
    course_description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    course_length: 7935,
    course_par: 71,
    course_slope: 92,
    course_address: "40648 Kensington Court",
    course_city: "Dolores",
    course_state: null,
  },
  {
    course_name: "Customer-focused object-oriented framework",
    course_description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    course_length: 6833,
    course_par: 71,
    course_slope: 61,
    course_address: "3647 Myrtle Parkway",
    course_city: "Yuandun",
    course_state: null,
  },
  {
    course_name: "Innovative homogeneous software",
    course_description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    course_length: 6420,
    course_par: 69,
    course_slope: 101,
    course_address: "74749 Dahle Lane",
    course_city: "Sutukung",
    course_state: null,
  },
  {
    course_name: "Optional reciprocal encryption",
    course_description:
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    course_length: 7804,
    course_par: 72,
    course_slope: 82,
    course_address: "08 Tennyson Crossing",
    course_city: "Bałtów",
    course_state: null,
  },
  {
    course_name: "Customizable hybrid infrastructure",
    course_description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    course_length: 5636,
    course_par: 71,
    course_slope: 151,
    course_address: "46 Esker Plaza",
    course_city: "Ōmagari",
    course_state: null,
  },
  {
    course_name: "Profit-focused hybrid initiative",
    course_description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    course_length: 6047,
    course_par: 69,
    course_slope: 105,
    course_address: "89 East Hill",
    course_city: "Sozopol",
    course_state: null,
  },
  {
    course_name: "Devolved regional intranet",
    course_description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    course_length: 6777,
    course_par: 70,
    course_slope: 123,
    course_address: "5745 Melby Avenue",
    course_city: "Sabugueiro",
    course_state: "07",
  },
  {
    course_name: "Intuitive even-keeled function",
    course_description:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    course_length: 5865,
    course_par: 69,
    course_slope: 66,
    course_address: "5671 Grasskamp Way",
    course_city: "Huibu",
    course_state: null,
  },
  {
    course_name: "Compatible web-enabled hub",
    course_description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    course_length: 7151,
    course_par: 71,
    course_slope: 145,
    course_address: "4085 Pawling Center",
    course_city: "Yonggu",
    course_state: null,
  },
];
